### ISSUE TITLE
ML-KEM-768.KeyGenDerand definition disagrees with Appendix B and C

### ISSUE THREAD

**Issue by FiloSottile** [dconnolly/draft-connolly-cfrg-xwing-kem#14]
Section 4 defines `ML-KEM-768.KeyGenDerand` as

> seed[0:32] is used for z in line 1 of algorithm 15 from [[MLKEM](https://dconnolly.github.io/draft-connolly-cfrg-xwing-kem/draft-connolly-cfrg-xwing-kem.html#MLKEM)] and seed[32:64] is used for d in line 1 of algorithm 12.

However, the implementation in Appendix B.3 does the opposite

```
z = seed[32:]
pk, sk2 = InnerKeyGen(seed[:32], params)
```

and the test vector in Appendix C passes when using seed[0:32] for d and seed[32:64] for z.

**Comment by bwesterb** [comment]
Whoops, you're right. Fixed on main.

**Comment by chris-wood** [comment]
Thanks @bwesterb. Any chance you'll cut a new version soon? I also ran into this issue.

**Comment by bwesterb** [comment]
Released `-02`.
