### ISSUE TITLE
replace with test vectors that re-use ML-KEM, X25519 values

### ISSUE THREAD

**Issue by jmcrawford45** [dconnolly/draft-connolly-cfrg-xwing-kem#18]
Hi all, thanks for putting this RFC together. I see that the test vectors are currently in need of an update, and I'm happy to update those if there aren't any outstanding dependencies. I wanted to clarify whether the TODO comment means to reuse the same key for subsequent test vectors or whether it means to reuse the X25519 test vectors from RFC 9180 (I'm not sure what the analog would be for MLKEM).

**Comment by bwesterb** [comment]
Thanks for reaching out and offering assistance. The test vectors are current, but of course, not final, as ML-KEM might change. What we would like to have, is a test suite that exercises corner-cases in X25519 and ML-KEM. For the ML-KEM draft, an example are those prepared by Filippo and by Sophie, see [this thread](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/aCAX-2QrUFw/m/hy5gwcESAAAJ). ML-KEM might change and for that matter X-Wing itself, so I feel it might be wasteful to spend a lot of time preparing exhaustive test vectors if we have to redo it. There are similar such test vectors for X25519 (but not in RFC 9180.)
