### ISSUE TITLE
KeyGen and KeyGen_internal mixed up in Section 4

### ISSUE THREAD

**Issue by FiloSottile** [dconnolly/draft-connolly-cfrg-xwing-kem#20]
Section 4 says X-Wing relies on `ML-KEM-768.KeyGen` and that to generate deterministic test vectors, we also use ML-`KEM-768.KeyGen_internal`. In the latest version, the former is not used and the latter is used in "production". (Which is good!)

**Comment by FiloSottile** [comment]
Also, aren't `UnpackDecapsulationKey` and `GenerateKeyPairDerand` the same function?

**Comment by bwesterb** [comment]
> Section 4 says X-Wing relies on `ML-KEM-768.KeyGen` and that to generate deterministic test vectors, we also use ML-`KEM-768.KeyGen_internal`. In the latest version, the former is not used and the latter is used in "production". (Which is good!)

Whoops, [corrected](https://github.com/dconnolly/draft-connolly-cfrg-xwing-kem/commit/496d38bc1d4c7f1c7d9bf8ecb358d37720e6c5e9), thanks.

> Also, aren't UnpackDecapsulationKey and GenerateKeyPairDerand the same function?

In a typical X-Wing implementation they'd be very close, but for RSA you have a reasonable implementation where they wouldn't. There GenerateKeyPairDerand would take a seed, and then increment two nonces until they find the primes. The decapsulation key would be the seed and the two nonces.

**Comment by FiloSottile** [comment]
> In a typical X-Wing implementation they'd be very close, but for RSA you have a reasonable implementation where they wouldn't. There GenerateKeyPairDerand would take a seed, and then increment two nonces until they find the primes. The decapsulation key would be the seed and the two nonces.

Oh yeah for sure not all KEMs use seeds as decapsulation keys, but XWing does, so reading only this spec it’s weird to see an undefined function be referenced which just happens to be the same as a differently named function.

**Comment by bwesterb** [comment]
Ah, I was speaking about such an API in general, but I see now it's confusing. Rephrased.
