### ISSUE TITLE
Consider a standardized domain separator string 

### ISSUE THREAD

**Issue by codespree** [dconnolly/draft-connolly-cfrg-xwing-kem#22]
I know the X-Wing ASCII art label is very cute (I like it too!)

But the composite KEM drafts use the hex of DER encoding of the OID as the dom-sep:
https://github.com/codespree/quantcrypt/blob/cef13f4c40b6da1bf2f2633e6e2bf28bca29994a/src/asn1/asn_util.rs#L25

Perhaps, in the interest of compatibility, this might be a good approach?

https://www.ietf.org/archive/id/draft-ietf-lamps-pq-composite-kem-05.html#name-domain-separators

For you to decide upon.

**Comment by bwesterb** [comment]
It would overflow the blocksize and thus add another keccak call. Also we can’t change xwing now that we have assigned codepoints.

**Comment by codespree** [comment]
Ok,

**Comment by codespree** [comment]
By the way, I updated my lib based on your last commit and comments:
https://github.com/codespree/quantcrypt/commit/ab05443b8964f72729e12ab1da466ca95cdc0a75
and moved to `Shake256` and updated the vectors in tests.

**Comment by bwesterb** [comment]
Great!Met een vriendelijke groet,        BasOn 25 Oct 2024, at 23:48, Varun Chatterji ***@***.***> wrote:﻿
By the way, I updated my lib based on your last commit and comments:
***@***.***
and moved to Shake256 and updated the vectors in tests.
