### ISSUE TITLE
Remove encapsulation key as argument to `Decapsulate()`

### ISSUE THREAD

**Issue by bwesterb** [dconnolly/draft-connolly-cfrg-xwing-kem#8]
We need the X25519 public key in the combiner to be IND-CCA robust, so we need it during `Decapsulation()`. However, that is quite unexpected for most APIs, and Mike Ounsworth points out that HSMs might find this difficult.

There are at least two options:

1. Recompute the X25519 public key from the secret key in the decapsulation in the spec. (Implementations can still cache the value during unpacking/keygen)
2. Include X25519 public key in the X-Wing private key, similar to ML-KEM. Suggested and preferred by @FiloSottile. 

I also lean to the latter.

**Comment by jedisct1** [comment]
From an implementer perspective, I'd lean for 2. as well.

**Comment by dconnolly** [comment]
I don't hate option 2, and it aligns with what ML-KEM does under the hood

**Comment by dconnolly** [comment]
closed with #10
