### ISSUE TITLE
Add section to track implementations

### ISSUE THREAD

**Issue by bwesterb** [dconnolly/draft-connolly-cfrg-xwing-kem#9]
- https://github.com/FiloSottile/mlkem768 (-00)
- https://github.com/cloudflare/circl/pull/471 (-00)

**Comment by rugo** [comment]
Here is an experimental Rust implementation: https://github.com/rugo/xwing-kem.rs

Also suffers from #8 and computes the x25519 pk on every call to `decaps`.

**Comment by dconnolly** [comment]
closed as resolved ✅
